# Generated by Django 5.1.4 on 2024-12-15 08:06

import django.db.models.manager
import user.utils.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(verbose_name='user id for backet')),
                ('products_id', models.JSONField(blank=True, null=True, verbose_name='product list')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='user id')),
                ('email', models.EmailField(max_length=126, unique=True)),
                ('name', models.CharField(max_length=126)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=6, validators=[user.utils.validators.validate_pincode])),
                ('is_verified_email', models.BooleanField(default=False)),
                ('is_verified_phone', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
